name: Cook, Stage & Package UE Project  # Choose a descriptive name for your workflow

on: # Define when this workflow should trigger (e.g., on push to main)
  push:
    branches:
      - main

jobs:
  build-ue-project:
    runs-on: windows-latest  # Use a Windows runner for UE projects
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cook, Stage & Package UE Project
      uses: OrchidIsle/UE5-Build-Project@latest
      with:
        RUNUAT_PATH: 'C:/Unreal Engine/UE5.3_Source/Engine/Build/BatchFiles/RunUAT.bat'
        UPROJECT_PATH: PiozaGameLauncher.uproject
        BUILD_CONFIG: Development
        PLATFORM: Win64
        CLEAN: true
        COOK: true
        STAGE: true
        PACKAGE: false
        PAK: false
        SERVER: false
        ARCHIVE: false
        ARCHIVE_PATH: 'Archives/PiozaGL/'
        NULLRHI: true
        EDITOR: true
        ENCRYPT_INI: true
        RELEASE: '1.0.0'
        PATCH: '0.9.0'
        MAPS: 'Map1,Map2'
        DELETE_PDB: true
